-- View: public.subscribers_view

-- DROP VIEW public.subscribers_view;

CREATE OR REPLACE VIEW public.subscribers_view
 AS
 SELECT subscribers.phone_number,
    subscribers.language,
    subscribers.sub01,
    subscribers.sub02,
    subscribers.sub03,
    subscribers.sub04,
    subscribers.sub05,
    subscribers.sub06,
    subscribers.sub07,
    subscribers.sub08,
    subscribers.sub09,
    subscribers.sub10,
    subscribers.sub11,
    subscribers.sub12,
    subscribers.sub13,
    subscribers.sub14,
    subscribers.sub15,
    subscribers.sub16,
    subscribers.sub17,
    subscribers.sub18,
    subscribers.sub19,
    subscribers.sub20,
    subscribers.sub21,
    subscribers.sub22,
    subscribers.sub23,
    subscribers.sub24,
    subscribers.sub25,
    subscribers.sub26,
    subscribers.sub27,
    subscribers.sub28,
    subscribers.sub29,
    subscribers.sub30,
    subscribers.sub31,
    subscribers.sub32,
    subscribers.sub33,
    subscribers.sub34,
    subscribers.sub35,
    subscribers.sub36,
    subscribers.sub37,
    subscribers.sub38,
    subscribers.sub39,
    subscribers.sub40,
    subscribers.sub41,
    subscribers.sub42,
    subscribers.sub43,
    subscribers.sub44,
    subscribers.sub45,
    subscribers.sub46,
    subscribers.sub47,
    subscribers.sub48,
    subscribers.sub49,
    subscribers.sub50,
    subscribers.sub51,
    subscribers.sub52,
    subscribers.sub53,
    subscribers.sub54,
    subscribers.sub55,
    subscribers.sub56,
    subscribers.sub57,
    subscribers.sub58
   FROM subscribers;

ALTER TABLE public.subscribers_view
    OWNER TO dev;

